### ISSUE TITLE
Read in "special" grid data

### ISSUE THREAD

**Issue by timothyas** [xgcm/xmitgcm#108]
There are some MITgcm files which get printed out that are "grid-like" but only show up in special cases, for instance:

- rLowC (etc) gets printed from write_grid when `debugLevel` >= `debugLevC`
- maskInC/W/S get printed when pkg/obcs is being used 
- AHybSigF when pressure coordinates are used (although I'm totally unfamiliar with this...)
- maskCtrlC/W/S get printed when pkg/ctrl is being used 
- probably others ... 

These are however separate from typical data variables because they don't have the ten digit time stamp, so adding them is not as simple as adding to `package_state_variables` which are read in as data vars. I would propose to do this by modifying `_get_all_grid_variables` so that after first grabbing the standard grid variables, it looks for these optional files with an adapted version of `_get_all_matching_prefixes`. 

Additionally, this seems related to #44, and could be addressed here as well.

I'm happy to implement this as I'm finally breaking my matlab addiction, but I wanted to see what you think before I code up a PR since I am a bit of a python and xmitgcm newbie.

**Comment by rabernat** [comment]
Sorry for the slow reply here.

Yes, we definitely would want the ability to read all this stuff! PR welcome!

**Comment by raphaeldussin** [comment]
fixed by #110 ?
