### ISSUE TITLE
model.get_dataset

### ISSUE THREAD

**Issue by jjocean1234** [xgcm/xmitgcm#159]
![Mitgcm](https://user-images.githubusercontent.com/52986313/61343208-fab08800-a81a-11e9-835b-14e68e81898c.png)

Hi, I am completely new to this and am having issues access the model datasets.
I get this error when I try & access the data. 
I believe I have downloaded the correct modules and am up to date.
Any help would be much appreciated.

**Comment by dhruvbalwada** [comment]
You might want to upgrade your dask library and try again.
