### ISSUE TITLE
test_llcreader url not found

### ISSUE THREAD

**Issue by malmans2** [xgcm/xmitgcm#163]
A couple of tests in `test_llcreader.py` are failing because url are not found:

- xmitgcm/test/test_llcreader.py::test_ecco_portal_load[2160] FAILED 
E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.nas.nasa.gov/file_system_down.html
- xmitgcm/test/test_llcreader.py::test_ecco_portal_load[4320] FAILED
E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.nas.nasa.gov/file_system_down.html

**Comment by rabernat** [comment]
Thanks for catching this @malmans2. I can reproduce it locally.

This is a useful test failure! It means the ecco data portal is down, which appears to be correct:
https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_2160/compressed/0000092160

For now we can ignore these failures. If the portal doesn't come back up again soon, we can contact the NAS folks and tell them to fix it.

**Comment by malmans2** [comment]
It's back online!
