### ISSUE TITLE
Cutting small pieces of data from very large data sets.

### ISSUE THREAD

**Issue by dhruvbalwada** [xgcm/xmitgcm#73]
Hello Everyone, 

I am in trying to perform a calculation that requires me to access a piece of MITgcm output from a very large output dataset. 

An example data set is - 
1680 mds files of W velocity, where each file is 1.2GB ~ 2TB of data. 
Each file has 2000X2000X76 grid points (X,Y,Z). 

I want to perform a calculation that requires me to load a section of this data,  with (800X800) points in space, and 1680 time points. The size of this little piece is 4GB only. 

However, when I try to load this data set the memory (RAM) usage goes through the roof (max out RAM usage, which is 1TB!), causing the notebook to die (kernel death, rather than an error). 

I am wondering if there is a workaround to this issue? 
Is there a way to trigger xmitgcm to be a bit more conservative on the memory usage, maybe at the loss of efficiency or something when the datasets are getting so large?

```python
data_dir = '/swot/SUM05/dbalwada/channel_beta/01km/free_slip_waves_hourly/'

npick = 1 # pick up every npick'th file as the original out is very dense (12 hours)

dt = int(3600/40)
T1 = int(712800)
T2 = int(864000+dt)
iters = range(T1, T2, dt*npick)

ds_free_slip = open_mdsdataset(data_dir, iters=iters,
delta_t=40, prefix=['W']
,ignore_unknown_vars=True, geometry='cartesian')
ds_free_slip
```

**Comment by rabernat** [comment]
@dhruvbalwada, can you provide a reproducible code sample of what you are trying to do?

**Comment by dhruvbalwada** [comment]
`data_dir = '/swot/SUM05/dbalwada/channel_beta/01km/free_slip_waves_hourly/'

npick = 1 # pick up every npick'th file as the original out is very dense (12 hours)
    
dt = int(3600/40)
T1 = int(712800)
T2 = int(864000+dt)
iters = range(T1, T2, dt*npick)

ds_free_slip = open_mdsdataset(data_dir,  iters=iters,
                             delta_t=40, prefix=['W']
                     ,ignore_unknown_vars=True, geometry='cartesian')
ds_free_slip`

**Comment by rabernat** [comment]
I am going to edit your comment to enable proper syntax highlighting.

**Comment by rabernat** [comment]
I'm so sorry, I accidentally hit delete and now I lost your comment

**Comment by rabernat** [comment]
Ok, got it back

**Comment by dhruvbalwada** [comment]
```
data_dir = '/swot/SUM05/dbalwada/channel_beta/01km/free_slip_waves_hourly/'

npick = 1 # pick up every npick'th file as the original out is very dense (12 hours)
    
dt = int(3600/40)
T1 = int(712800)
T2 = int(864000+dt)
iters = range(T1, T2, dt*npick)

ds_free_slip = open_mdsdataset(data_dir,  iters=iters,
                             delta_t=40, prefix=['W']
                     ,ignore_unknown_vars=True, geometry='cartesian')
ds_free_slip
```

the output is 

```
<xarray.Dataset>
Dimensions:  (XC: 2000, XG: 2000, YC: 2000, YG: 2000, Z: 76, Zl: 76, Zp1: 77, Zu: 76, time: 1681)
Coordinates:
  * XG       (XG) >f4 0.0 1000.0 2000.0 3000.0 4000.0 5000.0 6000.0 7000.0 ...
  * XC       (XC) >f4 500.0 1500.0 2500.0 3500.0 4500.0 5500.0 6500.0 7500.0 ...
  * YG       (YG) >f4 0.0 1000.0 2000.0 3000.0 4000.0 5000.0 6000.0 7000.0 ...
  * YC       (YC) >f4 500.0 1500.0 2500.0 3500.0 4500.0 5500.0 6500.0 7500.0 ...
  * Z        (Z) >f4 -0.5 -1.57 -2.79 -4.185 -5.78 -7.595 -9.66 -12.01 ...
  * Zl       (Zl) >f4 0.0 -1.0 -2.14 -3.44 -4.93 -6.63 -8.56 -10.76 -13.26 ...
  * Zu       (Zu) >f4 -1.0 -2.14 -3.44 -4.93 -6.63 -8.56 -10.76 -13.26 -16.1 ...
  * Zp1      (Zp1) >f4 0.0 -1.0 -2.14 -3.44 -4.93 -6.63 -8.56 -10.76 -13.26 ...
    dyC      (YG, XC) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    rAz      (YG, XG) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    Depth    (YC, XC) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    rAs      (YG, XC) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    dxC      (YC, XG) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    rAw      (YC, XG) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    dyG      (YC, XG) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    dxG      (YG, XC) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    rA       (YC, XC) >f4 dask.array<shape=(2000, 2000), chunksize=(2000, 2000)>
    PHrefF   (Zp1) >f4 dask.array<shape=(77,), chunksize=(77,)>
    PHrefC   (Z) >f4 dask.array<shape=(76,), chunksize=(76,)>
    drC      (Zp1) >f4 dask.array<shape=(77,), chunksize=(77,)>
    drF      (Z) >f4 dask.array<shape=(76,), chunksize=(76,)>
    hFacC    (Z, YC, XC) >f4 dask.array<shape=(76, 2000, 2000), chunksize=(76, 2000, 2000)>
    hFacW    (Z, YC, XG) >f4 dask.array<shape=(76, 2000, 2000), chunksize=(76, 2000, 2000)>
    hFacS    (Z, YG, XC) >f4 dask.array<shape=(76, 2000, 2000), chunksize=(76, 2000, 2000)>
    iter     (time) int64 dask.array<shape=(1681,), chunksize=(1,)>
  * time     (time) int64 28512000 28515600 28519200 28522800 28526400 ...
Data variables:
    W        (time, Zl, YC, XC) float32 dask.array<shape=(1681, 76, 2000, 2000), chunksize=(1, 76, 2000, 2000)>
```

**Comment by rabernat** [comment]
ok, so the chunk size shows that chunking did work. I had some optimism that #60 would help fix this, but I don't think so.

**Comment by rabernat** [comment]
> I want to perform a calculation that requires me to load a section of this data, with (800X800) points in space, and 1680 time points. The size of this little piece is 4GB only.
> 
> However, when I try to load this data set the memory (RAM) usage goes through the roof (max out RAM usage, which is 1TB!), causing the notebook to die (kernel death, rather than an error).

Can you post the code you are using to do these things?

**Comment by rabernat** [comment]
This brings to mind pydata/xarray#1396

**Comment by rabernat** [comment]
Can you also post the output of `xarray.show_versions()`?

**Comment by dhruvbalwada** [comment]
The data size : 
```
ds_free_slip.nbytes/(1024**3)
```
give 1907.24 GB. 

This is the data selection process 
```
ds_piece = ds_free_slip.W.sel(XC=slice(0,800e3), YC=slice(600e3,1400e3)).sel(Zl=-150., method='nearest')
ds_piece
```

which gives 

```
<xarray.DataArray 'W' (time: 1681, YC: 800, XC: 800)>
dask.array<shape=(1681, 800, 800), dtype=float32, chunksize=(1, 800, 800)>
Coordinates:
  * XC       (XC) >f4 500.0 1500.0 2500.0 3500.0 4500.0 5500.0 6500.0 7500.0 ...
  * YC       (YC) >f4 600500.0 601500.0 602500.0 603500.0 604500.0 605500.0 ...
    Zl       >f4 -146.88
    Depth    (YC, XC) >f4 dask.array<shape=(800, 800), chunksize=(800, 800)>
    rA       (YC, XC) >f4 dask.array<shape=(800, 800), chunksize=(800, 800)>
    iter     (time) int64 dask.array<shape=(1681,), chunksize=(1,)>
  * time     (time) int64 28512000 28515600 28519200 28522800 28526400 ...
Attributes:
    long_name:      Vertical Component of Velocity
    units:          m s-1
    standard_name:  sea_water_z_velocity
```

And size of this little piece is 
```
ds_piece.nbytes/(1024**3)
```
which is 4GB.

**Comment by dhruvbalwada** [comment]
Answer to 
`xr.show_versions()` 
is 
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.4.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.17.1.el7.centos.plus.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

xarray: 0.10.0
pandas: 0.21.0
numpy: 1.13.3
scipy: 1.0.0
netCDF4: 1.2.4
h5netcdf: None
Nio: None
bottleneck: None
cyordereddict: None
dask: 0.16.0
matplotlib: 2.1.0
cartopy: None
seaborn: 0.8.0
setuptools: 36.5.0.post20170921
pip: 9.0.1
conda: None
pytest: 3.2.5
IPython: 6.1.0
sphinx: None
```

**Comment by rabernat** [comment]
I can reproduce this issue on gyre.

**Comment by rabernat** [comment]
Here is a piece of the dask graph for `ds_piece`

![image](https://user-images.githubusercontent.com/1197350/37011081-76990ad8-20bc-11e8-98b9-8f47ab380b57.png)

**Comment by rabernat** [comment]
And here it is for `ds_free_slip.W.data.visualize()`

![image](https://user-images.githubusercontent.com/1197350/37011130-b5ae89a0-20bc-11e8-953c-5f985296f1d5.png)

**Comment by rabernat** [comment]
From these, the issue appears to be clear: the whole variable is being loaded before slicing (i.e. calls to `getitem`) takes place.

**Comment by rabernat** [comment]
@dhruvbalwada I believe I have tracked down part of the problem to the somewhat obscure dask bug referenced above.

**Comment by rabernat** [comment]
I confirmed that your calculation works much better (doesn't blow up; goes fast) if you call `open_mdsdataset` with `endian='='`. Of course, this screws up all your data by interpreting it as the wrong datatype. (You have to use `.isel` instead of `.sel` since the coordinates will be garbage.) But you can verify for yourself that it works. This means that the problem is with how dask handles big-endian datatypes.

Hopefully this can be fixed upstream in dask.

**Comment by dhruvbalwada** [comment]
Thanks for looking into this @rabernat and providing a temporary solution. I really appreciate this.

**Comment by rabernat** [comment]
I'm not sure it's a solution at all! Your data is useless with the wrong
datatype! But we have identified the problem.

**Comment by dhruvbalwada** [comment]
Good, the problem is not solved then. I guess then your remark about using isel instead of sel is also pointless, as I will just select a piece out of data that is trash, which does seem to be the case.

**Comment by rabernat** [comment]
With the wrong dtype, all your data is garbage.

As a temporary workaround, however, It might be possible to change the dtype *after* you have selected it. You can do this by creating a view of the data:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.view.html

**Comment by rabernat** [comment]
> I guess then your remark about using isel instead of sel is also pointless, as I will just select a piece out of data that is trash

It is not "pointless" insofar as it demonstrates the fundamental underlying issue. It is not useful for making an actual scientific calculation.

**Comment by rabernat** [comment]
To clarify what I mean, I think you can get the correct raw data back by doing `ds_piece.data.view(dtype='>f4')`. This will work as long as you haven't done any computations upstream but are just selecting data.

**Comment by rabernat** [comment]
This should be fixed by https://github.com/dask/dask/pull/3301. Can we check?

**Comment by dhruvbalwada** [comment]
I checked the effects of the update to dask on loading MITgcm output and the test data that you had created on the issue #3248 in dask. 

The test data with different choices of endianness now takes the same time to load. 

Data from MITgcm loaded with and without the option `endian='='` takes the same time to load.
