### ISSUE TITLE
xmitgcm being used for serving B-SOSE

### ISSUE THREAD

**Issue by mmazloff** [xgcm/xmitgcm#74]
Hello

I wanted to take the time to thank the xmitgcm developers for the software! I am just learning xmitgcm, but so far I am extremely impressed!  I am presently converting all BSOSE output to netcdf via xmitgcm. And I wanted to let you know that I credited it on the BSOSE page:
http://sose.ucsd.edu/BSOSE_iter105_solution.html 
"Most files processed into netcdf form using xmitgcm with grid information included.”
(I say most as there are a few derived ones, like neutral density, that I haven’t quite figured out yet…will get to it…)

Thanks for your work on this project! I look forward to continued use and learning more!

-Matt

**Comment by rabernat** [comment]
Thanks for the feedback Matt! Don't hesitate to raise any issues you encounter or suggest new features.
