### ISSUE TITLE
need to release v0.2.2

### ISSUE THREAD

**Issue by rabernat** [xgcm/xmitgcm#75]
0.2.1 was released in May 2017. There have been many bugfixes since then, but no release.

I would like to do the following before a release

- [ ] Fix #67
- [ ] Set up conda-forge packaging

**Comment by rabernat** [comment]
I no longer think it is practical to fix #67 before doing a new release. Fixing that issue properly will require a major refactor to how timesteps our handled.

@raphaeldussin, I would be happy if you could move ahead with the release process for xmitgcm v0.2.2.

**Comment by raphaeldussin** [comment]
Do we want the conda-forge for this release?

**Comment by rabernat** [comment]
Yes I think so. I would just imitate what @ocefpaf set up for xgcm.

**Comment by raphaeldussin** [comment]
ok! If I got it right, this is orthogonal and I can release first, then pypi then conda-forge.
I have a new version ready to be pushed. Just want to make sure I did it right : 

* cloned xgcm/xmitgcm
* update the development.rst with filtered content of git log (commit1)
* bumpversion patch (commit2)

If that's ok, I'll push to xgcm/xmitgcm master's

**Comment by rabernat** [comment]
Yes that sounds like a good plan. 

When in doubt, try to follow the procedure from xarray https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE

**Comment by raphaeldussin** [comment]
sounds good!

**Comment by raphaeldussin** [comment]
it's been released 10 days ago on pip. Working on the conda-forge this week

**Comment by rabernat** [comment]
You also need to make the new tag in git, push to master, and draft the [release](https://github.com/xgcm/xmitgcm/releases) on github ([steps 8 - 12](https://github.com/pydata/xarray/blob/master/HOW_TO_RELEASE)).

Ideally all of these things happen in very close temporal proximity to each other, so the "release" is a discrete event.

**Comment by rabernat** [comment]
When all this is done, we should announce the release on the mitgcm mailing list.

**Comment by rabernat** [comment]
> I can't add the requirements.txt with sphinx=1.6.7 to fix it because I don't own the project
> on readthedocs.

We are using an environment.yml (conda environment) rather than environment.txt (pip environment) for rtd.

You don't need to own the project on rtd to fix this. Just make a PR with the necessary updates to https://github.com/xgcm/xmitgcm/blob/master/doc/environment.yml.

**Comment by raphaeldussin** [comment]
got it! I may have found the problem in the build log
(see https://readthedocs.org/api/v2/build/7563226.txt)

The first phase works well, installing sphinx 1.2.3 as required. Only, after that comes
this command : 

conda install --yes --name stable mock pillow sphinx sphinx_rtd_theme

that triggers the update to sphinx 1.7.5. I don't know what controls this.

**Comment by rabernat** [comment]
It seems like that line is built into the build process. Weird. I wish there were a way to disable that.

Maybe open a new rtd issue?

**Comment by raphaeldussin** [comment]
apparently it is a known issue, waiting for conda update

https://github.com/rtfd/readthedocs.org/issues/3829

**Comment by raphaeldussin** [comment]
@ocefpaf @jbusecke are you ok to be listed as co-maintainers of the conda recipe ?

**Comment by ocefpaf** [comment]
> @ocefpaf @jbusecke are you ok to be listed as co-maintainers of the conda recipe ?

Sure.

**Comment by jbusecke** [comment]
Yup

Julius Busecke
