### ISSUE TITLE
commit 0ca23c2 doesn't work on anaconda3

### ISSUE THREAD

**Issue by raphaeldussin** [xgcm/xmitgcm#82]
doesn't pass the py.test:

E       NameError: name 'unicode' is not defined

removing or unicde on line 123 in mds_store.py works

**Comment by rabernat** [comment]
Yes, this appears to be failing on travis as well!
https://travis-ci.org/xgcm/xmitgcm/jobs/389877039

The full stack trace is:
```
        # get frame info for history
        frame = inspect.currentframe()
        _, _, _, arg_values = inspect.getargvalues(frame)
        del arg_values['frame']
        function_name = inspect.getframeinfo(frame)[2]
    
        # auto-detect whether to swap dims
        if swap_dims is None:
            if read_grid == False:
                swap_dims = False
            else:
                swap_dims = False if geometry in ('llc', 'curvilinear') else True
    
        # some checks for argument consistency
        if swap_dims and not read_grid:
            raise ValueError("If swap_dims==True, read_grid must be True.")
    
        # if prefix is passed as a string, force it to be a list
>       if type(prefix) is str or unicode:
E       NameError: name 'unicode' is not defined
```

I don't know how this bug emerged.

Could you try to fix the error and submit a pull request? It seems like `unicode` needs to be imported.

**Comment by raphaeldussin** [comment]
it seems that, since python3 is using unicode for all strings, the type unicode doesn't exist anymore.

https://stackoverflow.com/questions/6812031/how-to-make-unicode-string-with-python3

should we just remove the unicode section of the test?

**Comment by rabernat** [comment]
We need to support python 2 and 3. 

The tests I showed you on my machine today were in python 3. 

This all worked a few weeks ago. I’m not sure what changed.
